version = 0.1
[default.deploy.parameters]
stack_name = "mansfield-lambda"
resolve_s3 = true
s3_prefix = "mansfield-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "personal"
